### ISSUE TITLE
Why disabled "Cryptojacking Protection"?

### ISSUE THREAD

**Issue by beerisgood** [crssi/NextDNS-Config#1]

**Comment by crssi** [comment]
If you inspect cryptomining lists at https://github.com/nextdns/metadata/blob/master/security/cryptojacking.json, you will find out that https://oisd.nl/?p=inc  includes all (both) of those and a few more, except that OISD did a cleanup and also removed false positives out, where the NextDNS's one have a false positives.

One of those, for example, is `lib.rus.ec` listed in https://zerodot1.gitlab.io/CoinBlockerLists/hosts_browser, preventing opening `gen.lib.rus.ec`.

Also, reporting such and similar at NextDNS or some of theirs up-streams takes ages to resolve.
At the same time, all nova-days browser already have cryptomining protection out-of-the-box.

Off topic:
At the end it is very simple... if there are breakages, users will flee away and use the Internet unprotected and giving you inferno at the same time... or we make things a reasonably little "loose" and they will be happy users with a lot of protection behind the scene.

Inspect https://oisd.nl/?p=inc  and you will find it covers almost everything you have ever needed. Note that there are also lists included which are not revealed here (for example mine... but it is there for sure).

Huh... I hope you got an answer I wanted to give... not sure if I was good in expressing my opinion.

**Comment by beerisgood** [comment]
Makes sense.
Thank you! Solved 🍺
