### ISSUE TITLE
Allow Affiliate & Tracking Links

### ISSUE THREAD

**Issue by beerisgood** [crssi/NextDNS-Config#2]
This will allow stuff like

> ad.doubleclick.net
> www.googleadservices.com

https://github.com/nextdns/metadata/blob/master/privacy/affiliate-tracking-domains

**Comment by crssi** [comment]
I know... I was ranting about those before, but then I got a good chunk of log data to test such cases.

For the particular ones,... those `kick in` on google domains, where you are already visiting and denying those brings breakages.

If user is using `www.google.com` then the harm is already done and there is no need to make a living for the user harder.

But, please, check your logs and re-check... the minutes after `www.google.com` those kind shows up.
When you do, show me wrong and let me know if those appears also "randomly" when `www.google.com` did not happen just before.

**Comment by crssi** [comment]
Oh. And @beerisgood I am open to suggestions. I do value your opinion highly. Let me know your thinking.

**Comment by beerisgood** [comment]
I only ask because a lot of sites sadly use google adservices, doubleclick, ...

Will test some sites
 🍺

**Comment by crssi** [comment]
Cool. I will be happy to learn your findings. 

Cheers

**Comment by beerisgood** [comment]
Test will take more time as i don't visit random sites often and sites i visit, are mostly clean of tracking.

**Comment by beerisgood** [comment]
Sorry for long delay.

As i now use OISD list which include both domains in [whitelist](https://oisd.nl/excludes.php) i will close this issue now.
I also do some cleanup on [Kees'](https://github.com/Kees1958/W3C_annual_most_used_survey_blocklist/commits/master) list and remove e.g. googleadservices.

Let's keep it clean and nicely!
