### ISSUE TITLE
1Hosts (Lite)

### ISSUE THREAD

**Issue by beerisgood** [crssi/NextDNS-Config#4]
for more than 2 days [i report a false positive](https://github.com/badmojr/1Hosts/issues/94) to them, but after 4 commits not even an answer.

I don't need any such ignorance list maintainer.
Just want to let you know

**Comment by crssi** [comment]
I do not believe you are being ignored. Just that you haven't got through his life queue. 😉
What I have learned is that 1 week on github issues is blazing fast.

Just wait for a little longer.

**Comment by crssi** [comment]
I have also spotted the domain in question. Have a few other suggestions for him too, but wanted to collect enough (several weeks/months) of browsing logs for diff analysis fist.

**Comment by beerisgood** [comment]
Dev removed that domain 👍

**Comment by crssi** [comment]
I knew @badmojr had a serious reason preventing him to solve the problem before. 😉 

Cheers

**Comment by badmojr** [comment]
> I knew @badmojr had a serious reason preventing him to solve the problem before. 😉
> 
> Cheers

Indeed!

**Comment by beerisgood** [comment]
> > I knew @badmojr had a serious reason preventing him to solve the problem before. 😉
> > Cheers
> 
> Indeed!

Fair enough. I only make terrible experience with a lot list maintainer in the past.
So sorry for my hard critism.

**Comment by badmojr** [comment]
Nah! No one is above criticism.
Keep up the good work.
